import streamlit as st
st.header("SCV-Dashboard Prototype")
st.header("This is how it works:")
st.write("Underpinned are normalized statistics for each of the industries you are able to choose from.")
st.write("This is what you will be compared to. The output in resilience, efficiency and sustainability will be your score from 0-100 compared to the industry average:")
st.markdown('#')
st.image(image="scores.png")
st.markdown('#')
st.write("The formula for calculation of your Viability is the average of each score, with the focus-field of the company having a 110% weight.")
st.write("You will receive your scores numerically:")
st.markdown('#')
st.image(image="unified score.png")
st.markdown('#')
st.write("You will see a graph showing how you compare to your industry:")
st.markdown('#')
st.image(image="barchart.png")
st.markdown('#')
st.write("Another cool illustration is the Viability-Triangle. It shows how well you balance each factor of supply chain viability:")
st.markdown('#')
st.image(image="radar.png")